### ISSUE TITLE
Teacher Edit a class

### ISSUE THREAD

**Issue by olivdums** [Laspargus/theteachingproject#18]
### Why ?

Teacher must be able to edit a class

### To Do

- [x] Button "edit" on show#class
- [x] Create the edit view
- [x] Edit & Update methods into the class controller
- [x] Only admin can edit a class

### Must have

- [x] Class show view
- [x] Dashboard view
- [x] Teacher model
- [x] Class model

**Comment by nikkiHelloThp** [comment]
Closes: #18
